name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.71.1'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Push
        run: |
          git config --global user.email "a.urusihara@gmail.com"
          git config --global user.name "Akihiro Urushihara"
          mkdir workspace
          cd workspace
          git init
          git remote add origin https://${GH_TOKEN}@github.com/uakihir0/uakihir0.github.io
          git pull origin master
          mkdir -p socialhub
          rsync -av ../public/ ../workspace/socialhub/ --exclude '/.git/' --exclude '.DS_Store' --exclude '/socialhub/'
          echo "DirectoryIndex index.html" > .htaccess
          git add --all
          git commit -m "by GitHub Action CI (SHA ${GITHUB_SHA})"
          git push origin master